### ISSUE TITLE
Task switch without task switch events?

### ISSUE THREAD

**Issue by accolasia** [openmastery/plugins#11]
How is this even happening?  Investigate interleaving of taskIds...

**Comment by accolasia** [comment]
<img width="958" alt="screenshot 2016-12-21 06 57 58" src="https://cloud.githubusercontent.com/assets/2080316/21390149/fcc9d10e-c74a-11e6-956f-9449e515f12e.png">

**Comment by mlueders** [comment]
Could this have been b/c there were multiple instances of the plugins running in separate instances of intellij?
