### ISSUE TITLE
ExecutionActivity has negative duration?

### ISSUE THREAD

**Issue by accolasia** [openmastery/plugins#2]
News-MBP:.ideaflow janelle$ cat active_messages.log
ExternalActivity={"taskId":5,"durationInSeconds":41,"comment":null,"endTime":"2016-11-09T14:25:03"}
ExecutionActivity={"taskId":5,"durationInSeconds":-30220,"processName":"Plugin","exitCode":137,"executionTaskType":"Plugin","endTime":"2016-11-09T14:25:30","debug":false}

**Comment by mlueders** [comment]
have not seen recently, possible it's fixed; re-open if it happens again
