### ISSUE TITLE
How am I getting a null subtask comment? (not initial strategy)

### ISSUE THREAD

**Issue by accolasia** [openmastery/plugins#23]

**Comment by accolasia** [comment]
http://om-ideaflow.herokuapp.com/ideaflow/timeline/task/39

<img width="694" alt="screenshot 2016-12-29 19 02 10" src="https://cloud.githubusercontent.com/assets/2080316/21558002/522c3844-cdf9-11e6-8966-0ec35e59a555.png">

**Comment by mlueders** [comment]
doesn't seem to have happened recently - could be it has been fixed or could be intermittent; if it happens again, re-open
