### ISSUE TITLE
Upgrade to 0.15 fails

### ISSUE THREAD

**Issue by losingkeys** [openmastery/plugins#30]
## The error
![2017-01-14-101526_667x656_scrot](https://cloud.githubusercontent.com/assets/666493/21956283/125c1468-da43-11e6-9953-589616692048.png)
## Other info
- I was on 0.5, I hadn't upgraded in awhile
- I'm running Idea 2016.3.2 on Linux

**Comment by accolasia** [comment]
Fixed in 0.16
