### ISSUE TITLE
[5.] Slf4j logging in client tools prevents plugin from working in old Intellij versions

### ISSUE THREAD

**Issue by accolasia** [openmastery/plugins#32]
Intellij loads plugin with Intellij classloader which creates some challenges with library dependencies.

Later versions of Intellij import Slf4j, older versions of Intellij do not.  Versions of the library vary across versions.  Slf4j dependency being in client tools creates circumstances where IdeaFlowDX plugin explodes.

Avoid plugin explosions and find an alternative work around for logging.

**Comment by mlueders** [comment]
common-rest has been updated to exclude slf4j in the client and ideaflow has been updated to use updated version of common-rest
