### ISSUE TITLE
[3.] Formatted snippet source is always null?  Can we get a file name or something?

### ISSUE THREAD

**Issue by accolasia** [openmastery/plugins#35]
http://om-ideaflow.herokuapp.com/ideaflow/timeline/task/4/full

**Comment by accolasia** [comment]
<img width="867" alt="screenshot 2017-03-31 21 11 35" src="https://cloud.githubusercontent.com/assets/2080316/24574337/ad928d0a-1656-11e7-8540-01dca334f756.png">

**Comment by mlueders** [comment]
not a plugin issue, source is getting populated and pushed to the server
