### ISSUE TITLE
data not spooled to local log file when task hasn't been started

### ISSUE THREAD

**Issue by Blackbaud-GregHenry** [openmastery/plugins#6]
Updated IdeaFlow plugin to version 0.5 this morning.

Added a task for the story I'm working on but did not click the "Start a subtask" button. I was then able to click both `YAY!` and `WTF?!` several times and enter problems/resolutions. When I noticed that the activity wasn't being spooled to the log file, I clicked the "Start a subtask" button and now all activity is being spooled.

Intellij info:
IntelliJ IDEA 2016.2.5
Build #IU-162.2228.15, built on October 14, 2016
JRE: 1.8.0_112-release-287-b2 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

**Comment by mlueders** [comment]
While not specifically fixed, there have been many changes to the plugin recently and I can't seem to reproduce this scenario.  If it happens again with the latest (0.14+), reopen and I'll investigate further - closing for now.
